spring:
    application:
        name: Chinasoft_Project_Barbie_BackEnd
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://8.138.0.106:3306/Chinasoft_21Group?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
            username: root
            password: 15222843862Zyh!
    main:
        allow-circular-references: true

mybatis:
    #mapper配置文件
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.group21.entity
    configuration:
        #开启驼峰命名
        map-underscore-to-camel-case: true

logging:
    level:
        com:
            zzc:
                demo1:
                    mapper: debug
                    service: info
                    controller: info

chinasoft-project-barbie:
    jwt:
        #加密密钥
        secret-key: chinasoft-project-barbie
        #过期时间
        ttl: 7200000
        #前端传过来的令牌名称
        token-name: token


mqtt:
    hostUrl: tcp://8.138.0.106:1883
    username: admin
    password: 15222843862Zyh
    client-id: test1
    cleanSession: true
    reconnect: true
    timeout: 100
    keepAlive: 100
    defaultTopic: bcd
    isOpen: true
    qos: 1