spring:
    application:
        name: Chinasoft_Project_Barbie_BackEnd
        datasource:
            druid:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://8.138.0.106:3306/Chinasoft_21Group?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 15222843862Zyh!
mybatis:
    #mapper配置文件
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.sky.entity
    configuration:
        #开启驼峰命名
        map-underscore-to-camel-case: true

logging:
    level:
        com:
            zzc:
                demo1:
                    mapper: debug
                    service: info
                    controller: info